from pathlib import Path

p = Path("tis/DESIGN_JA.md")
text = p.read_text()

old_version = '''現行productのplaybackで使用するAndroidX Media3は **1.5.1** に固定し、対象LineageOS 21 / Android 14 treeの`prebuilts/misc`に偶然存在するMedia3版を暗黙利用しない。製品側でGoogle Maven由来の`media3-common:1.5.1`、`media3-exoplayer:1.5.1`、字幕Cue符号化に必要な`media3-extractor:1.5.1`と、それらPOMが要求するMedia3依存closureを同一version 1.5.1でcommit固定・hash検証してproduct-local prebuiltとして保持する。Soong導入はAOSP `prebuilts/misc/common/androidx-media3`と同じ`pom2bp`生成の`android_library_import` + `static_libs`方式を使う。製品root module名は`maleicacid_media3_common_1_5_1`、`maleicacid_media3_exoplayer_1_5_1`、`maleicacid_media3_extractor_1_5_1`に固定し、POM dependency closureにも`maleicacid_` prefixを付けてplatform moduleと衝突させない。TIS APKは必要なroot moduleを`static_libs`で明示参照する。platform側`androidx.media3.*` moduleへのfallback、異version混在、runtime download、Gradle解決は行わない。実装時にこのprebuilt closureとSoong moduleを追加できないtreeは現行product対象外とし、別versionへ黙示fallbackしない。

1.5.1を固定する理由は、現行設計が必要とする公開境界が同版で閉じるためである。videoのfirst-render commitは`Player.Listener.onRenderedFirstFrame()`、subtitle schedulingは`MimeTypes.APPLICATION_MEDIA3_CUES`を処理する`TextRenderer`、bitmap字幕表現は`Cue.bitmap`、Cue + durationのserializationは`CueEncoder`を使う。audio attributionは1.9系で導入された`AudioOutputProvider` / `AudioTrackAudioOutputProvider`を前提にせず、1.5.1の`DefaultAudioSink.AudioTrackProvider`と`DefaultAudioSink.Builder.setAudioTrackProvider()`だけを使う。したがってAndroid 14標準prebuiltの版差を隠して新APIを呼ぶ構成にはしない。'''
new_version = '''現行productのplaybackで使用するAndroidX Media3のbaseは **1.4.1** に固定し、対象LineageOS 21 / Android 14 treeの`prebuilts/misc`に偶然存在するMedia3版を暗黙利用しない。Media3 1.5.0は`compileSdk=35`へ移行すると同時に従来のmanual API-level outliningを削除し、non-Gradle buildではR8相当のautomatic API outliningを要求する。対象LineageOS 21 treeはAndroid 14世代のSoong / R8であるため、この追加toolchain前提を未証明のまま1.5.x AARへ持ち込まない。製品側ではGoogle Maven由来の`media3-common:1.4.1`、`media3-exoplayer:1.4.1`、`media3-extractor:1.4.1`とPOM dependency closureを同一version 1.4.1で固定する。

API 34のTV app AudioTrack attributionに必要な拡張点だけは、後続upstream 1.5.1の`DefaultAudioSink.AudioTrackProvider`、`DefaultAudioTrackProvider`、`DefaultAudioSink.Builder.setAudioTrackProvider()`に相当する変更を**1.4.1 `media3-exoplayer`へ限定backport**する。backportはAudioTrack生成factoryの差し替え境界だけに限定し、decoder、AudioSinkのwrite/clock、buffering、frame scheduling、track selectionその他のMedia3挙動を変更しない。upstream 1.4.1 artifact hash、backport patch hash、生成したproduct-local prebuilt hashを固定し、patch内容がこの境界以外へ広がった場合は別設計変更として扱う。

Soong導入はAOSP `prebuilts/misc/common/androidx-media3`と同じ`android_library_import` + `static_libs`方式を使う。製品root module名は`maleicacid_media3_common_1_4_1`、`maleicacid_media3_exoplayer_1_4_1_attribution`、`maleicacid_media3_extractor_1_4_1`に固定し、dependency closureにも`maleicacid_` prefixを付けてplatform moduleと衝突させない。TIS APKは必要なroot moduleを`static_libs`で明示参照する。platform側`androidx.media3.*` moduleへのfallback、異version混在、runtime download、Gradle解決、Media3 1.5.xを対象Android 14 R8で未検証のまま取り込むfallbackは行わない。

1.4.1には現行設計が必要とする`Player.Listener.onRenderedFirstFrame()`、`MimeTypes.APPLICATION_MEDIA3_CUES`を処理する`TextRenderer`、bitmap `Cue`、`CueEncoder`、`CUE_REPLACEMENT_BEHAVIOR_REPLACE`が存在する。したがってplayback clock / renderer / text timelineはupstream 1.4.1の標準ownershipに残し、製品差分はAudioTrack Builderへsession attributionを設定するfactory hookだけとする。'''
if text.count(old_version) != 1:
    raise SystemExit(f"version block count={text.count(old_version)}")
text = text.replace(old_version, new_version, 1)

old_first = '''first-frame availabilityのcommitはMedia3 `Player.Listener.onRenderedFirstFrame()`を使う。このcallbackはsurface設定、renderer reset、stream変更後にframeが初めてrenderされた時点のイベントなので、current playback generationとcurrent Surface generationへlistener tokenを結び付ける。`notifyVideoAvailable()`はこのcurrent tokenの`onRenderedFirstFrame()`を受け、current `sessionSurface`が有効、視聴制限でblockされておらず、同generationのplayer／video renderer errorがない場合だけ一度呼ぶ。Media3内部のframe-available、decoder output、clock進行、drop、旧generation／旧Surface callbackをfinal commitへ昇格させない。物理display/compositor fenceは要求せず、固定delay、独自clock、独自frame scheduler、hidden API、pixel probeも追加しない。'''
new_first = old_first + '''

MediaSync案は完成経路として採用しない。`MediaCodec.OnFrameRenderedListener`は`MediaSync.createInputSurface()`へのdecoder出力到達しか観測せず、`MediaSync.getTimestamp()`はcurrent playback positionのtemporal gateには使えても、そのcandidate video frameがMediaSyncからoutput `sessionSurface`へrenderされたかlate-dropされたかを区別しない。AOSP MediaSyncはaudio同期時にlate video bufferをrenderせずinputへ返す経路を持つため、audio由来media positionがcandidate PTSを越えた後でもcandidateがdrop済みという実行が成立する。この状態で`notifyVideoAvailable()`を発火すると、`TvInputService.Session`の「content rendered onto its surfaceがready for viewingになったら通知する」という契約を満たす根拠がない。CTSが`notifyVideoAvailable()` callback伝播を検査するだけで実Surface timingを検査していないこと、Tuner VTSがTISのpresentation timingを検査しないことは、このAPI前提条件を緩和する契約ではない。よって`OnFrameRendered` + `getTimestamp()` best-effort gateは診断・中間観測には使用可能でもavailabilityの最終commitには採用せず、final rendererがrender/dropを区別して返す現行Media3 ownershipを維持する。'''
if text.count(old_first) != 1:
    raise SystemExit(f"first frame block count={text.count(old_first)}")
text = text.replace(old_first, new_first, 1)

old_subtitle = '''字幕のpresentation clockとdisplay/clear schedulingはvideo/audioと同じMedia3 ExoPlayer timelineが唯一所有する。TIS、Rust JNI、`CaptionOverlayView`は独自timer、`player.currentPosition` polling loop、`SystemClock`比較、MediaSync position追従loopを持たない。ARIB字幕PESから得たPTSはvideo/audioと同じ33-bit 90 kHz unwrap規則でcurrent playback generationの`timeUs`へ変換し、libaribcaption rendererへそのPTSで描画要求する。rendererが返すRGBA8888画像と描画領域はKotlin側で`Bitmap`へ安全に所有権変換し、Media3 1.5.1のbitmap `Cue`へ変換する。

字幕用Media3 `SampleStream`はformatを`MimeTypes.APPLICATION_MEDIA3_CUES`とし、各字幕eventを`CueEncoder.encode(cues, durationUs)`でsample化する。sampleの`DecoderInputBuffer.timeUs`を字幕PTSに設定し、表示継続時間はlibaribcaption/ARIB字幕eventから得たdurationまたは次の明示clear境界としてencodeする。Media3 `TextRenderer`がplayerの`positionUs`に対してCueの開始・終了を評価し、current cue setを`TextOutput` / player cue callbackへ出す。`CaptionOverlayView`はそのcallbackで渡されたcurrent bitmap Cue群だけを合成し、空Cue群では即座に消去する。overlay自体は時刻判定を行わない。

字幕track無効化、`onSelectTrack(TYPE_SUBTITLE, null)`、retune、Surface/session release、playback generation変更ではsubtitle SampleStreamを無効化し、Media3 text rendererのcurrent cueをclearしてoverlayへ空Cue群を反映する。旧generationのlibaribcaption結果やCue callbackはgeneration tokenで破棄する。これにより既存future_workの「libaribcaption rendererのRGBA8888をKotlin overlayへ表示する」という完了条件を維持しつつ、表示・消去時刻のownerだけをMedia3 timelineへ固定する。future_workを独立timer実装の根拠として解釈してはならない。'''
new_subtitle = '''字幕のpresentation clockとdisplay/clear schedulingはvideo/audioと同じMedia3 ExoPlayer timelineが唯一所有する。TIS、Rust JNI、`CaptionOverlayView`は独自timer、`player.currentPosition` polling loop、`SystemClock`比較、MediaSync position追従loopを持たない。ARIB字幕PESから得たPTSはvideo/audioと同じ33-bit 90 kHz unwrap規則でcurrent playback generationの`timeUs`へ変換し、libaribcaption rendererへそのPTSで描画要求する。rendererが返すRGBA8888画像と描画領域はKotlin側で`Bitmap`へ安全に所有権変換し、Media3 1.4.1のbitmap `Cue`へ変換する。

字幕用Media3 `SampleStream`は`Format.sampleMimeType = MimeTypes.APPLICATION_MEDIA3_CUES`に加えて、**`Format.cueReplacementBehavior = CUE_REPLACEMENT_BEHAVIOR_REPLACE`を明示設定**する。defaultの`MERGE`には依存しない。各字幕eventのsampleは`DecoderInputBuffer.timeUs = subtitlePtsUs`とし、有限のlibaribcaption `wait_duration`は`CueEncoder.encode(cues, finiteDurationUs)`へそのまま渡す。`DURATION_INDEFINITE`は有限値へ推測変換せず、REPLACEでのみ許容される`C.TIME_UNSET`を`durationUs`としてencodeする。後続captionが到着した場合は、その後続PTSの新しいreplacement Cue sampleが前のindefinite Cueを置換するため、既にMedia3へ渡したsampleのdurationを遡って書き換えない。libaribcaption/ARIBの明示clearまたは当該PTSで表示すべき画像が空になるeventは、そのclear PTSに**空Cue listのreplacement sample**を`C.TIME_UNSET`で投入し、同じTextRenderer timeline上で消去する。

Media3 `TextRenderer`がplayerの`positionUs`に対してCueの開始・終了・replacementを評価し、current cue setを`TextOutput` / player cue callbackへ出す。`CaptionOverlayView`はそのcallbackで渡されたcurrent bitmap Cue群だけを合成し、空Cue群では即座に消去する。overlay自体は時刻判定を行わない。字幕track無効化、`onSelectTrack(TYPE_SUBTITLE, null)`、retune、Surface/session release、playback generation変更はPTS付きcaption eventではなくsession state transitionなので、subtitle SampleStreamを無効化すると同時にTextRenderer stateとoverlayを同期clearする。旧generationのlibaribcaption結果やCue callbackはgeneration tokenで破棄する。

bitmap Cueの`CueEncoder`経路はfreeではない。Media3 1.4.1の`Cue.toSerializableBundle()`はbitmapをlossless PNGへencodeしてParcel bytesへ格納し、`CueDecoder`側でPNGをBitmapへdecodeするため、RGBA8888 → Bitmap → PNG encode/Parcel → PNG decode → Bitmapというcopy/CPU負荷を持つ。この経路を字幕対応readyとする前に、製品profileの最大字幕plane/region更新頻度を使って、PNG encode/decode latency、peak allocation、GC、subtitle SampleStream backlogが既存のbounded memory/backpressure契約内に収まり、A/V playbackを阻害しないことを実機qualificationで確認する。未確認または上限超過を「たぶん軽い」として成功扱いにせず、そのprofileでは字幕対応を有効化しない。性能問題を独自timer、別clock、無制限queueで回避してはならない。

これにより既存future_workの「libaribcaption rendererのRGBA8888をKotlin overlayへ表示する」という完了条件を維持しつつ、表示・消去時刻のownerだけをMedia3 timelineへ固定する。future_workを独立timer実装の根拠として解釈してはならない。'''
if text.count(old_subtitle) != 1:
    raise SystemExit(f"subtitle block count={text.count(old_subtitle)}")
text = text.replace(old_subtitle, new_subtitle, 1)

old_attr = '''Tuner SDKのTRM接続にはframework由来`sessionId`を`Tuner(serviceContext, sessionId, useCase)`へ渡す。audio出力はMedia3が所有するが、Android 14（API 34）の公開`AudioTrack.Builder.setContext(sessionContext)`によるTV app attribution chainを失ってはならない。現行productではMedia3 1.5.1の`DefaultAudioTrackProvider`を継承したsession固有providerを使い、その1.5.1公開protected hook `customizeAudioTrackBuilder(AudioTrack.Builder)`だけをoverrideして`setContext(sessionContext)`を追加する。`DefaultRenderersFactory.buildAudioSink(...)`のoverrideでは`DefaultAudioSink.Builder(sessionContext).setAudioTrackProvider(sessionProvider).build()`を返す。sample rate、channel config、encoding、buffer size、audio attributes、audio session id、offload等のAudioTrack構成は`DefaultAudioTrackProvider`の標準実装に残し、TIS側へ複製しない。TISはAudioTrackへのwrite、playback head、clock、buffer schedulingを所有しない。Media3 1.9系で追加された別provider APIには依存しない。通常経路で素の`serviceContext`へ後退せず、2引数版／1引数版の互換経路から3引数通常経路へ黙示fallbackしない。session releaseまたはplayer置換後は旧`sessionContext`、旧player、旧AudioSinkを新generationへ再利用しない。'''
new_attr = '''Tuner SDKのTRM接続にはframework由来`sessionId`を`Tuner(serviceContext, sessionId, useCase)`へ渡す。audio出力はMedia3が所有するが、Android 14（API 34）の公開`AudioTrack.Builder.setContext(sessionContext)`によるTV app attribution chainを失ってはならない。現行productでは上記の**1.4.1 + upstream AudioTrackProvider限定backport**に含まれる`DefaultAudioTrackProvider`を継承したsession固有providerを使い、backportしたprotected hook `customizeAudioTrackBuilder(AudioTrack.Builder)`だけをoverrideして`setContext(sessionContext)`を追加する。`DefaultRenderersFactory.buildAudioSink(...)`のoverrideでは`DefaultAudioSink.Builder(sessionContext).setAudioTrackProvider(sessionProvider).build()`を返す。sample rate、channel config、encoding、buffer size、audio attributes、audio session id、offload等のAudioTrack構成はbackport元upstream `DefaultAudioTrackProvider`の標準実装に残し、TIS側へ複製しない。TISはAudioTrackへのwrite、playback head、clock、buffer schedulingを所有しない。Media3 1.5.x本体や1.9系の別provider APIには依存しない。通常経路で素の`serviceContext`へ後退せず、2引数版／1引数版の互換経路から3引数通常経路へ黙示fallbackしない。session releaseまたはplayer置換後は旧`sessionContext`、旧player、旧AudioSinkを新generationへ再利用しない。'''
if text.count(old_attr) != 1:
    raise SystemExit(f"attribution block count={text.count(old_attr)}")
text = text.replace(old_attr, new_attr, 1)

text = text.replace('Media3 1.5.1 `SampleStream`', 'Media3 1.4.1 `SampleStream`')
text = text.replace('同じMedia3 1.5.1 ExoPlayer', '同じMedia3 1.4.1 ExoPlayer')

p.write_text(text)
