from pathlib import Path
import re

R=Path('tuner_hal2')
def one(p,o,n):
 t=p.read_text(); c=t.count(o)
 if c!=1: raise SystemExit(f'{p}: anchor count {c}: {o[:80]!r}')
 p.write_text(t.replace(o,n,1))

# 10-25/59 FMQ site-local safety contracts.
p=R/'fmq/src/lib.rs'
items=[
('        let queue = unsafe { native_queue_create(num_bytes, configure_event_flag) };\n','        // SAFETY: arguments are values; the shim returns an opaque pointer and retains no Rust reference.\n        let queue = unsafe { native_queue_create(num_bytes, configure_event_flag) };\n        // POSTCONDITION: null is rejected; a non-null queue becomes this wrapper\'s sole native owner.\n'),
('        unsafe { native_queue_available_to_read(self.queue) }\n','        // SAFETY: self.queue is a live create-derived handle for the whole shared borrow.\n        let value = unsafe { native_queue_available_to_read(self.queue) };\n        // POSTCONDITION: only detached scalar metadata is returned; ownership is unchanged.\n        value\n'),
('        unsafe { native_queue_available_to_write(self.queue) }\n','        // SAFETY: self.queue is a live create-derived handle for the whole shared borrow.\n        let value = unsafe { native_queue_available_to_write(self.queue) };\n        // POSTCONDITION: only detached scalar metadata is returned; ownership is unchanged.\n        value\n'),
('        let status = unsafe { native_queue_write_checked(self.queue, ptr, len, &mut written) };\n','        // SAFETY: queue is live; ptr is readable for len bytes (or null when len==0), and written is a unique writable out-parameter.\n        let status = unsafe { native_queue_write_checked(self.queue, ptr, len, &mut written) };\n        // POSTCONDITION: the shim retains neither pointer; written is interpreted only through status.\n'),
('            unsafe { native_queue_read(self.queue, data.as_mut_ptr(), data.len()) }\n','            // SAFETY: queue is live and data provides an exclusive writable data.len()-byte region for this call.\n            let read = unsafe { native_queue_read(self.queue, data.as_mut_ptr(), data.len()) };\n            // POSTCONDITION: native retains no buffer pointer; the returned count describes this call only.\n            read\n'),
('        let status = unsafe { native_queue_read_exact(self.queue, data.as_mut_ptr(), data.len()) };\n','        // SAFETY: queue is live and data is an exclusive writable region of exactly data.len() bytes.\n        let status = unsafe { native_queue_read_exact(self.queue, data.as_mut_ptr(), data.len()) };\n        // POSTCONDITION: status==0 is the only state treated as a complete exact read; no pointer escapes.\n'),
('        unsafe { native_queue_wake(self.queue, bits) }\n','        // SAFETY: queue is live and bits is passed by value to the queue\'s EventFlag operation.\n        let status = unsafe { native_queue_wake(self.queue, bits) };\n        // POSTCONDITION: status is returned verbatim; queue ownership/lifetime is unchanged.\n        status\n'),
('        unsafe { native_queue_quantum(self.queue) }\n','        // SAFETY: queue is live; the shim reads descriptor metadata only.\n        let value = unsafe { native_queue_quantum(self.queue) };\n        // POSTCONDITION: only scalar descriptor metadata is returned.\n        value\n'),
('        unsafe { native_queue_flags(self.queue) }\n','        // SAFETY: queue is live; the shim reads descriptor metadata only.\n        let value = unsafe { native_queue_flags(self.queue) };\n        // POSTCONDITION: only scalar descriptor metadata is returned.\n        value\n'),
('        unsafe { native_queue_grantor_count(self.queue) }\n','        // SAFETY: queue is live; the shim reads the descriptor grantor count only.\n        let count = unsafe { native_queue_grantor_count(self.queue) };\n        // POSTCONDITION: count is detached metadata used as the later grantor index bound.\n        count\n'),
('        let ok = unsafe {\n            native_queue_grantor_at(self.queue, index, &mut fd_index, &mut offset, &mut extent)\n        };\n','        // SAFETY: queue is live; native validates index, and all three out-pointers are unique writable locals.\n        let ok = unsafe {\n            native_queue_grantor_at(self.queue, index, &mut fd_index, &mut offset, &mut extent)\n        };\n        // POSTCONDITION: out-values are observed only when true; false maps to None.\n'),
('        unsafe { native_queue_fd_count(self.queue) }\n','        // SAFETY: queue is live; the shim reads the descriptor FD count only.\n        let count = unsafe { native_queue_fd_count(self.queue) };\n        // POSTCONDITION: count is detached metadata used as the later FD index bound.\n        count\n'),
('        unsafe { native_queue_dup_fd_at(self.queue, index) }\n','        // SAFETY: queue is live and native validates index against its FD table.\n        let fd = unsafe { native_queue_dup_fd_at(self.queue, index) };\n        // POSTCONDITION: non-negative means a newly duplicated caller-owned FD; negative remains failure.\n        fd\n'),
('        unsafe { native_queue_int_count(self.queue) }\n','        // SAFETY: queue is live; the shim reads the descriptor integer count only.\n        let count = unsafe { native_queue_int_count(self.queue) };\n        // POSTCONDITION: count is detached metadata used as the later integer index bound.\n        count\n'),
('        let ok = unsafe { native_queue_int_at(self.queue, index, &mut value) };\n','        // SAFETY: queue is live; native validates index and value is a unique writable out-parameter.\n        let ok = unsafe { native_queue_int_at(self.queue, index, &mut value) };\n        // POSTCONDITION: value is observed only when true; false maps to None.\n'),
('        unsafe { native_queue_destroy(self.queue) };\n','        // SAFETY: this wrapper is the sole owner of the live create-derived handle and Drop executes its unique destroy.\n        unsafe { native_queue_destroy(self.queue) };\n        // POSTCONDITION: the native handle is lifetime-ended and is never used again.\n')]
for a,b in items: one(p,a,b)

# 26-35/59 AV backing safety contracts, exact current shapes.
p=R/'demux/src/av/shared_backing.rs'
items=[
('            let raw_fd = unsafe { tuner_dmabuf_heap_alloc_system(size_bytes) };\n','            // SAFETY: size_bytes is checked above; allocator receives no Rust pointer and returns a fresh FD or negative error.\n            let raw_fd = unsafe { tuner_dmabuf_heap_alloc_system(size_bytes) };\n            // POSTCONDITION: only a non-negative fresh FD proceeds to the unique File ownership transfer.\n'),
('            self.file = Some(unsafe { File::from_raw_fd(raw_fd) });\n','            // SAFETY: raw_fd is non-negative, fresh, and has no Rust owner; ownership transfers exactly once here.\n            self.file = Some(unsafe { File::from_raw_fd(raw_fd) });\n            // POSTCONDITION: self.file is the sole Rust owner responsible for closing that FD.\n'),
('        let mapped = unsafe {\n            mmap(\n                ptr::null_mut(),\n                map_len,\n','        // SAFETY: file is live, map_len is the checked full backing extent, offset is zero, and no Rust reference aliases the requested mapping.\n        let mapped = unsafe {\n            mmap(\n                ptr::null_mut(),\n                map_len,\n'),
('        if mapped == MAP_FAILED {\n            return Err(AvSharedBackingError::MappingFailed);\n        }\n        unsafe {\n            ptr::copy_nonoverlapping(\n                payload.as_ptr(),\n                (mapped as *mut u8).add(slot_index * self.slot_size),\n                payload.len(),\n            );\n        }\n        if unsafe { munmap(mapped, map_len) } != 0 {\n','        // POSTCONDITION: MAP_FAILED is rejected; otherwise mapped denotes map_len writable bytes until munmap.\n        if mapped == MAP_FAILED {\n            return Err(AvSharedBackingError::MappingFailed);\n        }\n        // SAFETY: slot validation proves offset + payload.len() <= map_len; source is readable, destination writable, and regions do not overlap.\n        unsafe {\n            ptr::copy_nonoverlapping(\n                payload.as_ptr(),\n                (mapped as *mut u8).add(slot_index * self.slot_size),\n                payload.len(),\n            );\n        }\n        // POSTCONDITION: exactly payload.len() bytes are copied into the selected mapped slot.\n        // SAFETY: mapped is the same successful mmap pointer and map_len is the identical mapping length; no mapped reference escapes.\n        if unsafe { munmap(mapped, map_len) } != 0 {\n'),
('            return Err(AvSharedBackingError::UnmappingFailed);\n        }\n        let Some(data_id) = self.data_id_allocator.issue() else {\n','            return Err(AvSharedBackingError::UnmappingFailed);\n        }\n        // POSTCONDITION: after munmap the mapping is treated as invalid and is never accessed again.\n        let Some(data_id) = self.data_id_allocator.issue() else {\n'),
('        let raw_fd = unsafe { tuner_dmabuf_heap_alloc_system(payload.len()) };\n','        // SAFETY: payload is non-empty and len is passed by value; allocator returns a fresh FD or negative error.\n        let raw_fd = unsafe { tuner_dmabuf_heap_alloc_system(payload.len()) };\n        // POSTCONDITION: only a non-negative fresh FD proceeds to unique File ownership transfer.\n'),
('        let file = Arc::new(unsafe { File::from_raw_fd(raw_fd) });\n','        // SAFETY: raw_fd is fresh, non-negative, and unowned by Rust; ownership transfers exactly once into File.\n        let file = Arc::new(unsafe { File::from_raw_fd(raw_fd) });\n        // POSTCONDITION: the Arc<File> owns close responsibility; raw_fd is never wrapped or closed separately.\n'),
('        let mapped = unsafe {\n            mmap(\n                ptr::null_mut(),\n                payload.len(),\n','        // SAFETY: file is live, payload.len() is a non-zero mapping extent, offset is zero, and no Rust reference aliases the requested mapping.\n        let mapped = unsafe {\n            mmap(\n                ptr::null_mut(),\n                payload.len(),\n'),
('        if mapped == MAP_FAILED {\n            return Err(AvSharedBackingError::MappingFailed);\n        }\n        unsafe {\n            ptr::copy_nonoverlapping(payload.as_ptr(), mapped as *mut u8, payload.len());\n        }\n        if unsafe { munmap(mapped, payload.len()) } != 0 {\n','        // POSTCONDITION: MAP_FAILED is rejected; otherwise mapped denotes payload.len() writable bytes until munmap.\n        if mapped == MAP_FAILED {\n            return Err(AvSharedBackingError::MappingFailed);\n        }\n        // SAFETY: payload is readable for len bytes, mapped is writable for the same len, and independent dmabuf storage cannot overlap the slice.\n        unsafe {\n            ptr::copy_nonoverlapping(payload.as_ptr(), mapped as *mut u8, payload.len());\n        }\n        // POSTCONDITION: the complete event payload occupies the mapped dmabuf region.\n        // SAFETY: mapped is the same successful mmap pointer and payload.len() is the identical mapping length; no mapped reference escapes.\n        if unsafe { munmap(mapped, payload.len()) } != 0 {\n'),
('            return Err(AvSharedBackingError::UnmappingFailed);\n        }\n        let file_identity = AvFileIdentity::from_file(&file)?;\n','            return Err(AvSharedBackingError::UnmappingFailed);\n        }\n        // POSTCONDITION: after munmap the event-local mapping is invalid and is never accessed again.\n        let file_identity = AvFileIdentity::from_file(&file)?;\n')]
for a,b in items: one(p,a,b)

# S-06..09 one-shot authority typing.
p=R/'service_runtime/src/registry.rs'
one(p,'#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub(crate) struct PreparedLnbAssignmentLease {\n','#[derive(Debug, Eq, PartialEq)]\n#[must_use = "prepared LNB assignment lease must be committed or aborted by value"]\npub(crate) struct PreparedLnbAssignmentLease {\n')
one(p,'#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub(crate) struct LnbAssignmentCleanupRecord {\n','#[derive(Debug, Eq, PartialEq)]\n#[must_use = "LNB assignment cleanup authority must be completed by value"]\npub(crate) struct LnbAssignmentCleanupRecord {\n')
p=R/'service_runtime/src/descrambler_session.rs'
one(p,'#[derive(Clone, Debug, Eq, PartialEq)]\nstruct PreparedDescramblerClearKey {\n','#[derive(Debug, Eq, PartialEq)]\n#[must_use = "prepared descrambler clear-key authority must be consumed by commit"]\nstruct PreparedDescramblerClearKey {\n')
p=R/'service_runtime/src/lnb_ops.rs'
one(p,'#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub(crate) struct FrontendFixedPowerPreparation {\n','#[derive(Debug, Eq, PartialEq)]\n#[must_use = "frontend fixed-power preparation must be completed or rolled back by value"]\npub(crate) struct FrontendFixedPowerPreparation {\n')
one(p,'    pub(crate) const fn frontend_id(self) -> FrontendRuntimeId {\n        self.frontend_id\n    }\n\n    pub(crate) const fn newly_retained(self) -> bool {\n        self.newly_retained\n    }\n','    pub(crate) const fn frontend_id(&self) -> FrontendRuntimeId {\n        self.frontend_id\n    }\n\n    pub(crate) const fn newly_retained(&self) -> bool {\n        self.newly_retained\n    }\n')

# S-05: move service-critical transition into service_runtime typed failure use-case.
p=R/'aidl_service/src/tuner_service/dvr_methods.rs'
one(p,'        if playback_kind.is_err()\n            || matches!(playback_kind, Ok(true)) && worker_start_result.is_err()\n        {\n            let shared_runtime = self.runtime();\n            if let Ok(mut runtime) = shared_runtime.lock() {\n                runtime.mark_service_critical();\n            }\n        }\n','')
p=R/'aidl_service/src/dvr_callback_delivery.rs'
one(p,'        guard.finish_callback_delivery_failure_use_case(CallbackDeliveryFailureReport::dvr(\n            handle.object_id(),\n            handle.generation(),\n            phase,\n            dvr_post_commit_phase,\n            primary,\n        ))\n','        if phase == CallbackDeliveryFailurePhase::PostCommitNotification {\n            guard.finish_dvr_post_commit_notification_failure_use_case(\n                handle.object_id(),\n                handle.generation(),\n                dvr_post_commit_phase,\n                primary,\n            )\n        } else {\n            guard.finish_callback_delivery_failure_use_case(CallbackDeliveryFailureReport::dvr(\n                handle.object_id(),\n                handle.generation(),\n                phase,\n                dvr_post_commit_phase,\n                primary,\n            ))\n        }\n')
p=R/'service_runtime/src/boot.rs'
t=p.read_text(); anchor='    pub fn finish_callback_delivery_failure_use_case(\n'
if t.count(anchor)!=1: raise SystemExit('callback failure anchor')
method='''    pub fn finish_dvr_post_commit_notification_failure_use_case(\n        &mut self,\n        object_id: AidlObjectId,\n        generation: AidlObjectGeneration,\n        phase: DvrPostCommitNotificationPhase,\n        primary: HalError,\n    ) -> Result<(), HalError> {\n        let service_critical = phase == DvrPostCommitNotificationPhase::StatusNotifierStart\n            && self\n                .dvr_status_metadata_snapshot_for_aidl_object(object_id, generation)\n                .map(|snapshot| snapshot.is_playback)\n                .unwrap_or(true);\n        self.finish_callback_delivery_failure_use_case(CallbackDeliveryFailureReport::dvr(\n            object_id, generation, CallbackDeliveryFailurePhase::PostCommitNotification, phase, primary,\n        ))?;\n        if service_critical { self.mark_service_critical(); }\n        Ok(())\n    }\n\n'''
p.write_text(t.replace(anchor,method+anchor,1))

print('batch1 v2 applied')
