[package]
name = "maleicacid-si-kotlin-bindings"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
maleicacid_arib_si_engine_core = { path = "../host_ci/core", features = ["kotlin-bindings"] }
serde-generate = { version = "=0.34.1", default-features = false, features = ["kotlin"] }
serde-reflection = "=0.6.0"
